#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
#
picom -f &
setxkmap tr &
xsetroot -cursor_name left_ptr
nitrogen --restore &
polybar &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.618
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true

bspc rule -a Firefox desktop='^2'

